//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chat.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change language, you need restart the application. Restart now?.
        /// </summary>
        public static string ChangeLanguageRequest {
            get {
                return ResourceManager.GetString("ChangeLanguageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishMI {
            get {
                return ResourceManager.GetString("EnglishMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to forward the port. Please restart the router..
        /// </summary>
        public static string ForwardPortError {
            get {
                return ResourceManager.GetString("ForwardPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string GermanMI {
            get {
                return ResourceManager.GetString("GermanMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters, numbers and underscores..
        /// </summary>
        public static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save login details.
        /// </summary>
        public static string KeepLogin {
            get {
                return ResourceManager.GetString("KeepLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMI {
            get {
                return ResourceManager.GetString("LanguageMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already connected.
        /// </summary>
        public static string LoginFailAlreadyConnected {
            get {
                return ResourceManager.GetString("LoginFailAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login has already been taken..
        /// </summary>
        public static string LoginTaken {
            get {
                return ResourceManager.GetString("LoginTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login window.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main room.
        /// </summary>
        public static string MainRoomCaption {
            get {
                return ResourceManager.GetString("MainRoomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat window.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkCaption {
            get {
                return ResourceManager.GetString("OkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can contain from 6 to 30 symbols. This may be letters, numbers, special characters..
        /// </summary>
        public static string PassError {
            get {
                return ResourceManager.GetString("PassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassLabel {
            get {
                return ResourceManager.GetString("PassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PassNoMatch {
            get {
                return ResourceManager.GetString("PassNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration complete..
        /// </summary>
        public static string RegComplete {
            get {
                return ResourceManager.GetString("RegComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationButton {
            get {
                return ResourceManager.GetString("RegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration window.
        /// </summary>
        public static string RegistrationWindowTitle {
            get {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string RussianMI {
            get {
                return ResourceManager.GetString("RussianMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain at least 3 character..
        /// </summary>
        public static string ShortLoginError {
            get {
                return ResourceManager.GetString("ShortLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 6 character..
        /// </summary>
        public static string ShortPassError {
            get {
                return ResourceManager.GetString("ShortPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UkrainianMI {
            get {
                return ResourceManager.GetString("UkrainianMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users:.
        /// </summary>
        public static string UsersCaption {
            get {
                return ResourceManager.GetString("UsersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
    }
}
